[package]
name = "rlua"
version = "0.18.1-pre0"
authors = ["kyren <kerriganw@gmail.com>"]
edition = "2018"
description = "High level bindings to Lua 5.x"
repository = "https://github.com/amethyst/rlua"
documentation = "https://docs.rs/rlua"
readme = "README.md"
keywords = ["lua"]
license = "MIT"

[badges]
circle-ci = { repository = "amethyst/rlua", branch = "master" }

[features]
default=["builtin-lua54"]
builtin-lua54=["lua54_sys"]
builtin-lua53=["lua53_sys"]
builtin-lua51=["lua51_sys"]

system-lua54=["builtin-lua54", "lua54_sys/lua54-pkg-config"]
system-lua53=["builtin-lua53", "lua53_sys/lua53-pkg-config"]
system-lua51=["builtin-lua51", "lua51_sys/lua51-pkg-config"]

# Enabled functions from the math module that have been deprecated
lua-compat-mathlib = []


[dependencies]
libc = { version = "0.2" }
num-traits = { version = "0.2.14" }
bitflags = { version = "1.0.4" }
bstr = {version = "0.2", features = ["std"], default_features = false }
lua54_sys = { path = "./crates/lua54_sys", optional = true }
lua53_sys = { path = "./crates/lua53_sys", optional = true }
lua51_sys = { path = "./crates/lua51_sys", optional = true }


[dev-dependencies]
rustyline = "6.0"
criterion = "0.3.0"
compiletest_rs = { version = "0.4", features = ["stable"] }

[[bench]]
name = "benchmark"
harness = false
