version: 2

jobs:
  build-default:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install libclang for bindgen
          command: |
            sudo apt-get update
            sudo apt-get install libclang-dev clang
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check Formatting
          command: |
              rustup component add rustfmt
              rustfmt --version
              cargo fmt --all -- --check --color=auto
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
  build-lua53:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-lua53-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check Formatting
          command: |
              rustup component add rustfmt
              rustfmt --version
              cargo fmt --all -- --check --color=auto
      - run:
          name: Build all targets
          command: cargo build --no-default-features --features=builtin-lua53 --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --no-default-features --features=builtin-lua53 --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-lua53-{{ arch }}-{{ checksum "Cargo.lock" }}
  build-lua51:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install Lua
          command: |
            sudo apt-get update -yqq
            sudo apt-get install -yqq liblua5.1-0-dev
            sudo apt-get clean
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - cargo-cache-lua51-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Check Formatting
          command: |
              rustup component add rustfmt
              rustfmt --version
              cargo fmt --all -- --check --color=auto
      - run:
          name: Build all targets
          command: cargo build --no-default-features --features=system-lua51 --all --all-targets
      - run:
          name: Run all tests
          command: cargo test --no-default-features --features=system-lua51 --all
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargo-cache-lua51-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  build:
    jobs:
      - "build-default"
      - "build-lua53"
      - "build-lua51"
